version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: morta7
      POSTGRES_USER: morta7
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: ./
    command: gunicorn morta7_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  db_data: